version: "3"

services:
  errbit:
    image: errbit
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./:/app
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - PORT=3002
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit
  mongo:
    image: mongo:4.1
    ports:
      - "27017"
